
server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_db?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      # 커넥션 기능 개신 (유휴상태의 커넥션의 제거여부를 검사할 때 유효성 검사 여부 결정)
      test-while-idle: true
      # 커넥션 유효 검사 시 사용할 쿼리 (DB 리소스를 가장 적게 사용할 쿼리 이용)
      # mysql : SELECT 1
      validation-query: SELECT 1
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: pasudo123@naver.com
    password: ''
    port: 587
    protocol: smtp
    debug: true
    smtp:
      auth: true
      starttls:
        enable: true

loggin:
  level:
    org.hibernate.SQL: DEBUG

app:
  jwt:
    header.prefix: Bearer
    header: Autorization
    secret: mySecret
    expiration: 900000
    claims:
      refresh:
        name: Refresh

  token:
    email:
      verification:
        duration: 3600000
    password:
      reset:
        duration: 3600000
    refresh:
      duration: 2592000000

  velocity:
    templates:
      location: /templates/


#Jackson properties
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
#spring.jackson.time-zone=UTC